---
title: "mebart-multivariate-demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mebart-multivariate-demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(MASS)
```

# Generate Synthetic Data

```{r}

# Fix random seed to make the results reproducible
set.seed(0)

# number of observations
n <- 100
p <- 2

# variance of measurement error and output, respectively
sigma_meas <- 0.01 * diag(x=1, nrow=p, ncol=p)
sigma_y <- 0.1 # standard deviation

# X prior info
x_mu = rep(0, p)
x_sigma = 0.3^2*diag(x=1, nrow=p, ncol=p)

# Generate x values uniformly and add measurement error
x_true <- MASS::mvrnorm(n=n, mu=x_mu, Sigma=x_sigma)
x_meas <- x_true + MASS::mvrnorm(n=n, mu=rep(0, p), Sigma=sigma_meas)
y_true <- 1 * (x_true[,1] >= 0) + 2 * (x_true[,2] >= 0)
y_obs <- y_true + rnorm(n, 0, sigma_y)

# Convert to df
df_me <- data.frame(x_meas, y=y_obs)

```

# Plot Raw Data

```{r}

ggplot(df_me) +
    geom_point(aes(x = X1, y = X2, color = y)) +
    scale_color_gradient(low = "blue", high = "red") +
    labs(title = "Synthetic Data with Measurement Error", x = "X1", y = "X2") +
    theme_minimal() +
    theme(legend.position="none")

```

# Fit BART and meBART Models


```{r}


f = file()
sink(f)

# Parameters
ndpost <- 2000 # (Default: 1000L)
nskip <- 200 # (Default: 100L)
ntree <- 50 # (Default: 200L)

# Vanilla BART
set.seed(0)
mdl_BART <- BART::wbart(df_me[,1:2], df_me$y,
                         nskip=nskip, ndpost=ndpost, ntree=ntree)

# meBART
set.seed(0)
mdl_meBART <- meBART::mebart_cont(df_me[,1:2], df_me$y, 
                         nskip=nskip, ndpost=ndpost, ntree=ntree, 
                         meas_error_sigma=sigma_meas,
                         x_mu=x_mu,
                         x_sigma=x_sigma)

closeAllConnections()

cat("Time taken for Vanilla BART: ", mdl_BART$proc.time[[3]], "s\n", sep="")
cat("Time taken for meBART: ", mdl_meBART$proc.time[[3]], "s\n", sep="")


```

# Plot Sigma Posterior Draws

```{r}

sigma_df <- data.frame(iter_num = seq_along(mdl_BART$sigma), sigma = mdl_BART$sigma, 
                 Method = rep("Vanilla BART", length(mdl_BART$sigma)))
sigma_df <- rbind(sigma_df, data.frame(iter_num = seq_along(mdl_meBART$sigma), sigma = mdl_meBART$sigma, 
                 Method = rep("meBART", length(mdl_meBART$sigma))))
colnames(sigma_df) <- c("iter_num", "sigma", "method")

sigma_df$method <- factor(sigma_df$method, levels = c("Vanilla BART", "meBART"))


# Create the ggplot line plot
sigma_plot <- ggplot(sigma_df, aes(x = iter_num, y = sigma, color=method)) +
    geom_line() +
    labs(x = "MCMC Iteration", y = TeX("sigma, $\\sigma$"), title = "Posterior Draws of Sigma") +
    geom_hline(yintercept=sigma_y, color="black", linetype="dashed")


sigma_plot

```

# Plot Prediction Contours


```{r}

df1 <- expand.grid(X1 = seq(-1, 1, length.out = 50),
                  X2 = seq(-1, 1, length.out = 50))

y <- colMeans(predict(mdl_BART, newdata = as.matrix(df1)))
df1$y <- y
df1$method <- "BART"

df2 <- expand.grid(X1 = seq(-1, 1, length.out = 50),
                  X2 = seq(-1, 1, length.out = 50))

y <- colMeans(predict(mdl_meBART, newdata = as.matrix(df2)))
df2$y <- y
df2$method <- "meBART"

df <- rbind(df1, df2)

ggplot(df, aes(x = X1, y = X2, z = y)) +
    facet_wrap(~method) +
    geom_contour_filled(bins = 15) +
    coord_fixed() +
    theme_minimal() +
    guides(fill = guide_legend(title = "Y Value")) +
    labs(title = "BART vs. meBART Prediction Contours", x = "X1", y = "X2")
```
