---
title: "mebart-demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mebart-demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(meBART)
library(tidyverse)
library(latex2exp)
library(ggridges)
```

# Toy Example

$$f(x) = 1_{[0.5, \infty)}(x)$$

# Generate Synthetic Data

```{r}

# Fix random seed to make the results reproducible
set.seed(0)

# number of observations
n <- 100

# variance of measurement error and output, respectively
sigma_meas <- 0.1
sigma_y <- 0.1

# Generate x values uniformly and add measurement error
x_true <- runif(n, 0, 1)
x_meas <- x_true + rnorm(n, 0, sigma_meas)
y_true <- 1 * (x_true >= 0.5)
y_obs <- y_true + rnorm(n, 0, sigma_y)

# Convert to df
df_me <- data.frame(X=x_meas, y=y_obs)
```



```{r}

# Parameters
ndpost <- 1000 # (Default: 1000L)
nskip <- 100 # (Default: 100L)
ntree <- 200 # (Default: 200L)

proposal_sd = 0.10


# Vanilla BART
set.seed(0)
mdl_BART <- BART::wbart(df_me$X, df_me$y, 
                         nskip=nskip, ndpost=ndpost, ntree=ntree)

# meBART
set.seed(0)
mdl_meBART <- meBART::mebart(df_me$X, df_me$y, 
                         nskip=nskip, ndpost=ndpost, ntree=ntree, 
                         proposal_sd=proposal_sd)


```



```{r}


values <- mdl_BART$treedraws$cutpoints[[1]]
output <- predict(mdl_BART, data.frame(values))# [500:1000,]
means <- colMeans(output)

lower_CI <- c()
upper_CI <- c()

for (i in 1:ncol(output)) {
    lower_CI <- c(lower_CI, quantile(output[,i], 0.025))
    upper_CI <- c(upper_CI, quantile(output[,i], 0.975))
}

ci_df <- data.frame(X=values, y=means, lower_CI=lower_CI, upper_CI=upper_CI)

ci_df$model <- "Vanilla BART"


values <- mdl_meBART$treedraws$cutpoints[[1]]
output <- predict(mdl_meBART, data.frame(values))# [500:1000,]
means <- colMeans(output)

lower_CI <- c()
upper_CI <- c()

for (i in 1:ncol(output)) {
    lower_CI <- c(lower_CI, quantile(output[,i], 0.025))
    upper_CI <- c(upper_CI, quantile(output[,i], 0.975))
}

ci_df2 <- data.frame(X=values, y=means, lower_CI=lower_CI, upper_CI=upper_CI)

ci_df2$model <- "meBART"

ci_df_combined <- rbind(ci_df, ci_df2)

ci_df_combined$model <- factor(ci_df_combined$model, levels = c("Vanilla BART", "meBART"))


mse_BART <- mean((mdl_BART$yhat.train.mean - y_true)^2)
mse_meBART <- mean((mdl_meBART$yhat.train.mean - y_true)^2)


ci_plot <- ggplot(ci_df_combined) +
    facet_grid(cols = vars(model)) +
    geom_line(aes(x=X, y=y), linetype=3) +
    geom_ribbon(aes(x=X, ymin=lower_CI, ymax=upper_CI), alpha=0.2) +
    labs(title = "meBART: Mean Prediction with 95% CI", x = "X", y = "Y") +
    geom_point(data=df_me, aes(x = X, y = y), color="#619CFF") +
    scale_x_continuous(breaks = seq(-0.2, 1.2, 0.2)) +
    scale_y_continuous(limits=c(-0.2, 1.2), breaks = seq(-0.2, 1.2, 0.2)) +
    annotate("segment", x = 0, xend = 0.5, y = 0, yend = 0, linetype = "solid") +
    annotate("segment", x = 0.5, xend = 1, y = 1, yend = 1, linetype = "solid") +
    annotate("point", x = 0.5, y = 0, size = 3, shape = 1) +
    annotate("point", x = 0.5, y = 1, size = 3, shape = 16) +
    scale_x_continuous(limits = c(-0.2, 1.2), breaks = seq(-0.2, 1.2, 0.2)) +
    scale_y_continuous(limits = c(-0.25, 1.25), breaks = seq(-0.2, 1.2, 0.2))
    coord_fixed(ratio=1)



ci_plot

```

