---
title: "analysis"
output: html_document
---


```{r}
library(tidyverse)
library(pROC)
```



```{r}

set.seed(0)
n <- nrow(df)

train_size <- floor(0.8 * n)
train_indices <- sample(1:n, size = train_size)

df_train <- df[train_indices, 2:8]
df_test <- df[-train_indices, 2:8]

```




```{r}

mdl_lr <- glm(BMI ~ ., data = df_train)

summary(mdl_lr)

print(paste0("Pseudo R squared: ", 1 - mdl_lr$deviance / mdl_lr$null.deviance))

```


```{r}

X <- as.data.frame(df_train[,1:6])
y <- df_train$BMI

set.seed(0)
mdl_BART <- BART::wbart(X, y)

```


```{r}

X <- as.data.frame(df_train[,1:6])
y <- df_train$BMI

x_mu <- colMeans(X)
x_sigma <- var(X)
# meas_error_sigma <- diag(c(1, 20, 20))
# meas_error_sigma <- diag(c(0.1, 0.1, 10))
# meas_error_sigma <- diag(c(0.05, 0.05, 5))

# meas_error_sigma <- diag(c(0.02, 0.02, 0.1)) # /2
meas_error_sigma <- 0.2*diag(6) # /3

```

```{r}


set.seed(0)
mdl_meBART <- meBART::mebart_cont(X, y,
                                    meas_error_sigma = meas_error_sigma,
                                    x_mu = x_mu,
                                    x_sigma = x_sigma)
```


# Training Results


```{r}
# Training Results
X_train <- as.data.frame(df_train[,1:6])
y_train <- df_train$BMI

pred_lr <- predict(mdl_lr, df_train)
pred_BART  <- predict(mdl_BART,  X_train)
pred_meBART  <- predict(mdl_meBART,  X_train)
pred_meBART2  <- mdl_meBART$yhat.train.mean



```


```{r}

# Print the MSE for each model
cat("MSE for Linear Regression:", mean((pred_lr - y_train)^2), "\n")
cat("MSE for BART:", mean((pred_BART - y_train)^2), "\n")
cat("MSE for meBART:", mean((pred_meBART - y_train)^2), "\n")
cat("MSE for meBART2:", mean((pred_meBART2 - y_train)^2), "\n")


```


# Testing Results


```{r}
# Testing Results

X_test <- as.data.frame(df_test[,1:6])
y_test <- df_test$BMI

pred_lr <- predict(mdl_lr, df_test)
pred_BART  <- predict(mdl_BART,  X_test)
pred_meBART  <- predict(mdl_meBART,  X_test)



```


```{r}


# Print the MSE for each model
cat("MSE for Linear Regression:", mean((pred_lr - y_test)^2), "\n")
cat("MSE for BART:", mean((pred_BART - y_test)^2), "\n")
cat("MSE for meBART:", mean((pred_meBART - y_test)^2), "\n")



```



```{r}
# Test empirical coverage probability
# BART
ci_BART <- t(apply(pred_BART, 2, quantile, probs = c(0.025, 0.975)))
coverage_BART <- mean((y_test >= ci_BART[,1]) & (y_test <= ci_BART[,2]))
print(paste("Empirical coverage probability for BART:", coverage_BART))

# meBART
ci_meBART <- t(apply(pred_meBART, 2, quantile, probs = c(0.025, 0.975)))
coverage_meBART <- mean((y_test >= ci_meBART[,1]) & (y_test <= ci_meBART[,2]))
print(paste("Empirical coverage probability for meBART:", coverage_meBART))


```


```{r}
plot(mdl_BART$sigma)
```

```{r}
plot(mdl_meBART$sigma)
```
















