---
title: "EDA"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}

## If you haven't downloaded data yet
url <- "https://static-content.springer.com/esm/art%3A10.1038%2Fs41591-022-01688-4/MediaObjects/41591_2022_1688_MOESM3_ESM.xlsx"

download.file(url, destfile = "fromentin_etal_IHD.xlsx", mode="wb")
```




```{r}

sheets <- readxl::excel_sheets("fromentin_etal_IHD.xlsx")

legends <- readxl::read_excel("fromentin_etal_IHD.xlsx", sheet="Legends")



df_ST9  <- readxl::read_excel("fromentin_etal_IHD.xlsx", sheet="ST9", skip=1)
# df_ST10 <- readxl::read_excel("41591_2022_1688_MOESM3_ESM.xlsx", sheet="ST10", skip=1)
# df_ST11 <- readxl::read_excel("41591_2022_1688_MOESM3_ESM.xlsx", sheet="ST11", skip=1)
# df_ST12 <- readxl::read_excel("41591_2022_1688_MOESM3_ESM.xlsx", sheet="ST12", skip=1)
# df_ST13 <- readxl::read_excel("41591_2022_1688_MOESM3_ESM.xlsx", sheet="ST13", skip=1)
# df_ST14 <- readxl::read_excel("41591_2022_1688_MOESM3_ESM.xlsx", sheet="ST14", skip=1)

```

```{r}

df_ST9  <- readxl::read_excel("fromentin_etal_IHD.xlsx", sheet="ST9", skip=1)

df <- df_ST9 %>%
    select("ID", "Systolic blood pressure (mmHg)", "Diastolic blood pressure (mmHg)",
           "Fasting plasma triglycerides (mmol/L)", "Fasting plasma adiponectin (mg/L)", 
           "Fasting plasma CRP (mg/L)", "HbA1c (%)", "BMI (kg/m²)") %>%
    rename(
      SBP = "Systolic blood pressure (mmHg)",
      DBP = "Diastolic blood pressure (mmHg)",
      TGs = "Fasting plasma triglycerides (mmol/L)",
      Adi = "Fasting plasma adiponectin (mg/L)",
      CRP = "Fasting plasma CRP (mg/L)",
      HbA1c = "HbA1c (%)",
      BMI = "BMI (kg/m²)"
    ) %>%
    mutate_at(vars("ID"), factor) %>%
    mutate_at(vars("SBP", "DBP", "TGs", "Adi", "CRP", "HbA1c", "BMI"), as.numeric) %>%
    drop_na()

df[2:8] <- scale(df[2:8])

```



```{r}

# data <- df %>%
#     pivot_longer(cols = c("SBP", "DBP", "TGs", "Adi", "CRP", "HbA1c", "BMI"),
#                  names_to = "variable",
#                  values_to = "count")
# 
# ggplot(data, aes(x = count, fill=variable)) +
#     geom_histogram(position = "identity", alpha=0.5)



vars <- c("SBP", "DBP", "TGs", "Adi", "CRP", "HbA1c", "BMI")

for (var in vars){
    p <- ggplot(df, aes_string(x = var)) +
        geom_histogram(position = "identity", alpha=0.5, bins=30) +
        ggtitle(var)
    print(p)
}


```

