---
title: "Analysis"
output: html_document
---


```{r}
library(tidyverse)
library(pROC)
```


```{r}
# Get average variances of longitudinal measurements

tmp <- cWBC %>% 
    filter(wbc %in% c("neutrophils", "lymphocytes", "monocytes")) %>%
    group_by(pid, wbc) %>%
    summarise(var = var(count, na.rm=TRUE), .groups = "drop") %>%
    group_by(wbc) %>%
    summarise(mean_var = mean(var, na.rm=TRUE), .groups = "drop")

```



```{r}

set.seed(0)
n <- nrow(df_final)

df <- df_final %>%
    mutate(monocytes = log(monocytes + 1),
           lymphocytes = log(lymphocytes + 1),
           neutrophils = log(neutrophils + 1))

train_size <- floor(0.8 * n)
train_indices <- sample(1:n, size = train_size)

df_train <- df[train_indices, ]
df_test <- df[-train_indices, ]

```




```{r}

mdl_lr <- glm(sick_14_days_later ~ ., data = df_train, family = "binomial")

summary(mdl_lr)

```


```{r}

X <- as.data.frame(df_train[,1:3])
y <- as.vector(as.integer(df_train$sick_14_days_later) - 1)

set.seed(0)
mdl_BART <- BART::pbart(X, y)

```


```{r}

X <- as.data.frame(df_train[,1:3])
y <- as.vector(as.integer(df_train$sick_14_days_later) - 1)

x_mu <- colMeans(X)
x_sigma <- var(X)
# meas_error_sigma <- diag(c(1, 20, 20))
# meas_error_sigma <- diag(c(0.1, 0.1, 10))
# meas_error_sigma <- diag(c(0.05, 0.05, 5))

# meas_error_sigma <- diag(c(0.02, 0.02, 0.1)) # /2
meas_error_sigma <- diag(c(0.01, 0.01, 0.05)) # /3

```

```{r}


set.seed(0)
mdl_meBART <- meBART::mebart_probit(X, y,
                                    meas_error_sigma = meas_error_sigma,
                                    x_mu = x_mu,
                                    x_sigma = x_sigma)
```


# Training Results


```{r}
# Training Results

X_train <- as.data.frame(df_train[,1:3])
y_train <- as.vector(as.integer(df_train$sick_14_days_later) - 1)

X_test <- as.data.frame(df_test[,1:3])
y_test <- as.vector(as.integer(df_test$sick_14_days_later) - 1)

pred_lr <- predict(mdl_lr, df_train, type="response")
pred_BART  <- predict(mdl_BART,  X_train)$prob.test.mean
pred_meBART  <- predict(mdl_meBART,  X_train)$prob.test.mean
pred_meBART2  <- mdl_meBART$prob.train.mean

# 
# 
# # Create ROC objects for each model
roc_lr <- roc(y_train, pred_lr)
roc_BART  <- roc(y_train, pred_BART)
roc_meBART  <- roc(y_train, pred_meBART)
roc_meBART2  <- roc(y_train, pred_meBART2)

```


```{r}



# Combine the ROC objects into a list
roc_list <- list(
  "Logistic Regression" = roc_lr,
  "BART" = roc_BART,
  "meBART" = roc_meBART,
  "meBART2" = roc_meBART2
)

# Plot using ggroc
ggroc(roc_list) +
  ggtitle("ROC Curves on Training Data") +
  xlab("1 - Specificity (False Positive Rate)") +
  ylab("Sensitivity (True Positive Rate)") +
  geom_abline(intercept = 1, slope = 1, color = "grey", linetype = "dashed") +
  theme_minimal() +
  labs(color = "Model") # Legend title

```


```{r}
# Print the AUC for each model
cat("AUC for Logistic Regression:", auc(roc_lr), "\n")
cat("AUC for BART:", auc(roc_BART), "\n")
cat("AUC for meBART:", auc(roc_meBART), "\n")
cat("AUC for meBART2:", auc(roc_meBART2), "\n")

```


# Testing Results


```{r}
# Testing Results

X_train <- as.data.frame(df_train[,1:3])
y_train <- as.vector(as.integer(df_train$sick_14_days_later) - 1)

X_test <- as.data.frame(df_test[,1:3])
y_test <- as.vector(as.integer(df_test$sick_14_days_later) - 1)

pred_lr <- predict(mdl_lr, df_test, type="response")
pred_BART  <- predict(mdl_BART,  X_test)$prob.test.mean
pred_meBART  <- predict(mdl_meBART,  X_test)$prob.test.mean
pred_meBART2  <- mdl_meBART$prob.train.mean

# 
# 
# # Create ROC objects for each model
roc_lr <- roc(y_test, pred_lr)
roc_BART  <- roc(y_test, pred_BART)
roc_meBART  <- roc(y_test, pred_meBART)
# roc_meBART2  <- roc(y, pred_meBART2)

```


```{r}



# Combine the ROC objects into a list
roc_list <- list(
  "Logistic Regression" = roc_lr,
  "BART" = roc_BART,
  "meBART" = roc_meBART
  #"meBART2" = roc_meBART2
)

# Plot using ggroc
ggroc(roc_list) +
  ggtitle("ROC Curves for Testing Data") +
  xlab("1 - Specificity (False Positive Rate)") +
  ylab("Sensitivity (True Positive Rate)") +
  geom_abline(intercept = 1, slope = 1, color = "grey", linetype = "dashed") +
  theme_minimal() +
  labs(color = "Model") # Legend title

```


```{r}
# Print the AUC for each model
cat("AUC for Logistic Regression:", auc(roc_lr), "\n")
cat("AUC for BART:", auc(roc_BART), "\n")
cat("AUC for meBART:", auc(roc_meBART), "\n")
# cat("AUC for meBART2:", auc(roc_meBART2), "\n")

```






```{r}
# Accuracy
preds_lr <- as.integer(pred_lr > 0.5)
preds_BART  <- as.integer(pred_BART > 0.5)
preds_meBART  <- as.integer(pred_meBART > 0.5)
preds_meBART2  <- as.integer(pred_meBART2 > 0.5)

print(paste0("Accuracy for Logistic Regression: ", mean(preds_lr == y)))
print(paste0("Accuracy for BART: ", mean(preds_BART == y)))
print(paste0("Accuracy for meBART: ", mean(preds_meBART == y)))
print(paste0("Accuracy for meBART2: ", mean(preds_meBART2 == y)))

# Precision
print(paste0("Precision for Logistic Regression: ", caret::posPredValue(factor(preds_lr), factor(y))))
print(paste0("Precision for BART: ", caret::posPredValue(factor(preds_BART), factor(y))))
print(paste0("Precision for meBART: ", caret::posPredValue(factor(preds_meBART), factor(y))))
print(paste0("Precision for meBART2: ", caret::posPredValue(factor(preds_meBART2), factor(y))))

# Recall / Sensitivity
print(paste0("Sensitivity for Logistic Regression: ", caret::sensitivity(factor(preds_lr), factor(y), pos="1")))
print(paste0("Sensitivity for BART: ", caret::sensitivity(factor(preds_BART), factor(y))))
print(paste0("Sensitivity for meBART: ", caret::sensitivity(factor(preds_meBART), factor(y))))
print(paste0("Sensitivity for meBART2: ", caret::sensitivity(factor(preds_meBART2), factor(y))))

# Specificity 
print(paste0("Specificity for Logistic Regression: ", caret::specificity(factor(preds_lr), factor(y))))
print(paste0("Specificity for BART: ", caret::specificity(factor(preds_BART), factor(y))))
print(paste0("Specificity for meBART: ", caret::specificity(factor(preds_meBART), factor(y))))
print(paste0("Specificity for meBART2: ", caret::specificity(factor(preds_meBART2), factor(y))))


```




















