---
title: "data_cleaning"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
setwd("./vignettes/schluter_etal_immune")


## Uncomment if you have not downloaded data yet
# url <- "https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-020-2971-8/MediaObjects/41586_2020_2971_MOESM3_ESM.zip"
# 
# download.file(url, destfile = "schluter_etal_immune.zip")
# 
# # List files in the zip archive
# zip_contents <- unzip("schluter_etal_immune.zip", list = TRUE)
# 
# # Filter out problematic files (e.g., those with "Icon" or "__MACOSX")
# valid_files <- zip_contents$Name[!grepl("Icon|__MACOSX", zip_contents$Name)]
# 
# # Unzip only the valid files
# unzip("schluter_etal_immune.zip", files = valid_files, exdir = "data", junkpaths = TRUE)


```


```{r}

## Use this code to load in all data files
# data_dir <- "./data/"
# list_of_files = list.files(path = data_dir)
# filenames <- basename(list_of_files)
# filenames <- filenames[grepl("\\.csv$", filenames)]
# 
# for (filename in filenames){
# 
#   assign(sub("\\.csv$", "", filename), read_csv(paste0(data_dir, filename), show_col_types = FALSE))
#   
# }


## Use this code to load in specific data files
cWBC <- read_csv("./data/cWBC.csv", show_col_types = FALSE)
cINFECTION <- read_csv("./data/cINFECTION.csv", show_col_types = FALSE)

```


```{r}

WBC <- cWBC %>% 
    select(-`...1`) %>%
    mutate(across(c("pid", "wbc", "exclude_reason"), as.factor)) %>%
    filter(wbc %in% c("neutrophils", "lymphocytes", "monocytes")) %>%
    mutate(across(c("eday", "anon-date", "anon-bmt-date"), as.integer)) %>%
    drop_na(count) %>%
    filter(is.na(exclude_reason)) %>%
    select(-exclude_reason) %>%
    distinct(`pid`, `wbc`, `anon-date`, .keep_all=TRUE) %>%
    group_by(pid) %>%
    filter(`anon-bmt-date` == min(`anon-bmt-date`)) %>%
    ungroup() %>%
    pivot_wider(names_from = "wbc", values_from = "count")

INFECTION <- cINFECTION %>%
    select(-c(`...1`, `value`, `infectious_agent`)) %>%
    distinct() %>%
    mutate(infection = "yes")


combined_df <- left_join(WBC, INFECTION, by=c("pid", "anon-date")) %>%
    mutate(infection = replace_na(infection, "no")) %>%
    mutate(across(c("pid", "infection"), as.factor)) %>%
    group_by(pid) %>%
    fill("anon-bmt-date", .direction = "downup") %>%
    ungroup() %>%
    mutate(days_since_bmt = `anon-date` - `anon-bmt-date`) %>%
    select(-c(`eday`, `anon-bmt-date`, `anon-date`))


```


```{r}
missing_21_groups <- combined_df %>%
    group_by(pid) %>%
    summarise(has_21 = any(days_since_bmt==21)) %>%
    filter(!has_21) %>%
    pull("pid")

missing_35_groups <- combined_df %>%
    group_by(pid) %>%
    summarise(has_35 = any(days_since_bmt==35)) %>%
    filter(!has_35) %>%
    pull("pid")
```



```{r}
# Create missing rows
rows_to_add_21 <- tibble(
    pid = missing_21_groups,
    days_since_bmt = 21
)

rows_to_add_35 <- tibble(
    pid = missing_35_groups,
    days_since_bmt = 35
)

# Combine with original data
df_fixed <- combined_df %>%
    bind_rows(rows_to_add_21) %>%
    bind_rows(rows_to_add_35)

```

```{r}
library(zoo)

df_imputed <- df_fixed %>%
    arrange(pid, days_since_bmt) %>%
    group_by(pid) %>%
    mutate(monocytes = na.approx(monocytes, x = days_since_bmt, na.rm = FALSE)) %>%
    mutate(lymphocytes = na.approx(lymphocytes, x = days_since_bmt, na.rm = FALSE)) %>%
    mutate(neutrophils = na.approx(neutrophils, x = days_since_bmt, na.rm = FALSE)) %>%
    ungroup()

```

```{r}
df_final <- df_imputed %>%
    group_by(pid) %>%
    mutate(
        sick_14_days_later = map_lgl(days_since_bmt, function(d) {
            any(infection[days_since_bmt %in% (d+1):(d + 14)] == "yes", na.rm = TRUE)
        })
    ) %>%
    ungroup() %>%
    filter(days_since_bmt == 21) %>%
    select(monocytes, lymphocytes, neutrophils, sick_14_days_later) %>%
    drop_na() %>%
    mutate(sick_14_days_later = as.factor(as.integer(sick_14_days_later)))
```



```{r}
# Class Imbalance

print(paste0("Proportion of sick 14 days later: ", mean(df_final$sick_14_days_later == "1")))

print(paste0("# of negative labels: ", sum(df_final$sick_14_days_later == "0")))
print(paste0("# of positive labels: ", sum(df_final$sick_14_days_later == "1")))


```



